### ISSUE TITLE
Support for cookie based login.

### ISSUE THREAD

**Issue by dreamss** [kodi-pvr/pvr.iptvsimple#114]
In kodi m3u8 stream urls can have the headers in the path in the form of "http://streamurl.m3u8|Cookie=x=y"

when I load said urls on my m3u8 in simple iptv addon, it lists the streams but wont play it. I was able to recompile the addon for libreelec.pi2  since my cookies are almost 2k long.

I cannot post the url im using since its not public but will message it to the main dev if he wants to help out. thanks

**Comment by afedchin** [comment]
try win proper header: like this http://streamurl.m3u|Set-Cookie=x%3Dy

**Comment by eracknaphobia** [comment]
Hi, I'm seeing an issue where my cookie is being truncated. My stream urls are very long (about 1200 characters) due to the cookie length.  Seems the stream url gets cut off at about 1024 characters? This obviously won't allow the stream to play because the cookie is incorrect. Can you confirm this is the case?

**Comment by Jalle19** [comment]
AFAIK that has been fixed in master

**Comment by Jalle19** [comment]
The line length limitation has been fixed in master
