### ISSUE TITLE
Change the EPG time Value from Slider to textbox

### ISSUE THREAD

**Issue by SkyBird1980** [kodi-pvr/pvr.iptvsimple#125]
if you use a touch screen, handling the slider is very difficult. please change it (or just add) a similar textbox.

**Comment by afedchin** [comment]
IPTV Simple has no UI and has no define any UI behavior. Your issue is related to a skin which you are using

**Comment by Jalle19** [comment]
@afedchin I think he's talking about the EPG offset setting in the addon settings

**Comment by SkyBird1980** [comment]
yes, thats it. next time i use a screenshot.

**Comment by Jalle19** [comment]
After having thought some more about this, changing the setting to a text box makes it less user-friendly since we have to allow fractional numbers, and there are more than one way of writing those (dot vs. comma). If the slider is too small for your touch screen device it is more of a skin issue than an issue with this addon.
