### ISSUE TITLE
[feature request] how could you separate VOD from the EPG and channel listings? 

### ISSUE THREAD

**Issue by sentriz** [kodi-pvr/pvr.iptvsimple#126]
Hello, my IPTV provider has a lot of VOD, and it all gets put at the end of the EPG. so say I have 200 channels, their EPG, then 700+ movies with no EPG. I could filter them out in Kodi group settings, but what's a better way to manage them?
Thank you

**Comment by Jalle19** [comment]
You as the user is responsible for using a playlist that suits you. Just because your particular pirate content service tacks on a bunch of movies at the end of their playlists doesn't mean we can add hacks to the addon just to get rid of those. I suggest you download the playlist and use a local copy of it instead where you have removed the entries you do not want.
