### ISSUE TITLE
undefined symbol: get_addon

### ISSUE THREAD

**Issue by Durlyn** [kodi-pvr/pvr.iptvsimple#148]
kodi v18.0-ALPHA1 Git:20170807-a8fe8e3
pvr.iptvsimple 3.2.0

in log: 
ERROR: Unable to resolve: /pvr.iptvsimple.so.3.2.0 get_addon, reason: /usr/local/lib64/kodi/addons/pvr.iptvsimple/pvr.iptvsimple.so.3.2.0: undefined symbol: get_addon.

**Comment by Jalle19** [comment]
Which was the last version that worked for you?

**Comment by MilhouseVH** [comment]
@Jalle19: The problem starts with #147.

Working fine: Test build [#0806](https://forum.kodi.tv/showthread.php?tid=298461&pid=2628359#pid2628359)
Unable to enable due to `get_addon`: Test build [#0807](https://forum.kodi.tv/showthread.php?tid=298461&pid=2628759#pid2628759)

With #147 reverted, the addon can be enabled successfully on Linux.

But if #147 is included, the above `get_addon` error is reported (this is also with a Kodi build that includes https://github.com/xbmc/xbmc/pull/12646, as this Kodi PR seems to have no effect).

**Comment by Jalle19** [comment]
ping @afedchin
