### ISSUE TITLE
[Windows] - Wrong EPG Times due to DST (1 Hour Out)

### ISSUE THREAD

**Issue by matthuisman** [kodi-pvr/pvr.iptvsimple#158]
Windows only.
In LibreELEC (Linux), the times are correct.

NZ has just switched to DST so we are now UTC + 13:00.
In Windows, the time is correct and Windows does display right time and is aware it is DST.

However, in KODI - all the EPG programs are out by an hour.
If I set a +1 offset in the settings, they are corrected.

Looks like the issue could be here:
https://github.com/kodi-pvr/pvr.iptvsimple/blob/6e44490841e31e149b1d71348fc29df4a04f89d9/src/PVRIptvData.cpp#L831

**_get_timezone (does not include DST) is used for Windows
tm_gmtoff (includes DST) is used for all other arch.**

It looks like Windows was using tm_gmtoff until the below pull request (October 2016) swapped it to _get_timezone.
https://github.com/kodi-pvr/pvr.iptvsimple/pull/90/files

This may explain why a user reported it's fine in KODI 16:
https://forum.kodi.tv/showthread.php?tid=315206&pid=2618530#pid2618530

TEMP SOLUTION:
1) Go to the PVR IPTV Simple Client Settings and set the Offset to +1.
2) Then go-to the KODI PVR / TV Settings -> Guide -> Clear Data
3) When daylight savings ends, set the offset to 0, and clear the guide data again.

**Comment by Jalle19** [comment]
@afedchin

**Comment by matthuisman** [comment]
Any updates on this? @afedchin @Jalle19

**Comment by afedchin** [comment]
I have no time to fix this right now

**Comment by MCTyler** [comment]
Perfect! 
TEMP SOLUTION:

Go to the PVR IPTV Simple Client Settings and set the Offset to +1.
Then go-to the KODI PVR / TV Settings -> Guide -> Clear Data
When daylight savings ends, set the offset to 0, and clear the guide data again.

**Comment by matthuisman** [comment]
@ksooo @afedchin 
Anyone keen to look at this issue from 2017?

**Comment by ksooo** [comment]
I don't use  iptvsimple.

**Comment by matthuisman** [comment]
Oh, I just had seen you had been last to commit so assumed you might have took over maintaining it.

And to be honest, I don't use it either. 
I use a TvHeadend back-end.

But I did spot the bug when testing other things.
And I was trying to clean up my issues list.

**Comment by palinek** [comment]
@matthuisman you can take a look in #190

**Comment by buers** [comment]
The following patch should solve the issue with wrong EPG times under Windows. Can anybody please test it and then apply it. (I myself do not have setup things to compile Kodi. However, I verified with a small test program, that the _mkgmtime() function does the right thing under Windows here).

[code]
--- PVRIptvData.cpp.old Sun May 05 21:53:05 2019
+++ PVRIptvData.cpp     Sun May 05 21:55:51 2019
@@ -822,22 +822,21 @@
   timeinfo.tm_year -= 1900;
   timeinfo.tm_isdst = -1;

-  std::time_t current_time;
-  std::time(&current_time);
-  long offset = 0;
-#ifndef TARGET_WINDOWS
-  offset = -std::localtime(&current_time)->tm_gmtoff;
-#else
-  _get_timezone(&offset);
-#endif // TARGET_WINDOWS
-
   long offset_of_date = (hours * 60 * 60) + (minutes * 60);
   if (sign == '-')
   {
     offset_of_date = -offset_of_date;
   }

+#ifndef TARGET_WINDOWS
+  std::time_t current_time;
+  std::time(&current_time);
+  long offset = 0;
+  offset = -std::localtime(&current_time)->tm_gmtoff;
   return mktime(&timeinfo) - offset_of_date - offset;
+#endif
+  return _mkgmtime(&timeinfo) - offset_of_date;
+#endif // TARGET_WINDOWS
 }

 PVRIptvChannel * PVRIptvData::FindChannel(const std::string &strId, const std::string &strName)
[/code]
BTW: There is at least one other problem with the code, even under UNIX systems: it assumes that the offset between local time and UTC is constant (which in general is not the case, because auf daylight saving). So on Unix systems, simple IPTV player will typically show wrong time stamps in EPG, when the next daylight saving change is close. My patch will avoid this problem.

I assume, that the fix under UNIX systems would be, to use

return timegm(&timeinfo) - offset_of_date;

instead of the tm_gmtoff hack. If it is not clear, what I mean, I can easily give a complete patch.

The code is a bit horrible anyway. Not a single comment in the function. The function is returning int, but should really return time_t. But I have too little overview over the whole framework, to fix this. (This type of errors yielded in year 2000 problem, in *many* security issues, …)

**Comment by matthuisman** [comment]
@buers
You may want to make a pull request with changes

I think it's about time this got fixed :)

**Comment by Sorien** [comment]
there is PR https://github.com/kodi-pvr/pvr.iptvsimple/pull/190 almost year old and not even reviewed :/

**Comment by palinek** [comment]
> there is PR #190 almost year old and not even reviewed :/

Huh...I've already forgotten about that :)

**Comment by buers** [comment]
Sorry, I was not aware, that there was already a patch created for this issue.

@Sorien, are you sure, this was not reviewed? When I click on your link, it seems there was a check, that failed? I personally don't understand it yet, but I fear anyway, that that patch might be wrong-

@palinek; have you checked your patch? To me it looks, like it uses the DiffBetweenUTCAndLocalTime correction with the wrong sign.

Originally, I wanted to use almost exactly the same method you are using - comparing gmtime and localtime and using the difference as correction. After some thought, I used _mkgmtime and timegm instead. Otherwise, it will be very difficult, to get the timestamps close to the change to DST correct. In my timezone (Berlin) only 1 hour each year is affected. On the other side of the world, more …

Here is my test driver, which rather carefully tests many timestamps over decades (However, I am not testing offsets in the timestamps - I never have seen any example, that uses them). I tried to modify your code only slightly. ParseDateTime_buers() is my fix to the problem, ParseDateTime() yours. (I am ignoring your scanning changes for this discussion). I tried it on Debian and Windows. I cannot really judge, if it will work on all Kodi platforms.

BTW. Using int instead of time_t really looks wrong. You are using unsigned for a difference, that can be positive or negative. That really is even worse. (I am aware, that it won't make a difference in the result on typical platforms).

@matthuisman : Sorry, while I am a rather old guy with decades of experience in development, GitHub is embarrassingly new to me. Therefore, I had hoped, anybody experienced here can pick up my patch and do with it, whatever is needed …

`#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#ifdef _WIN32
#define TARGET_WINDOWS 1
#endif

#if defined(TARGET_WINDOWS)
# define LOCALTIME_R(src, dst) localtime_s(dst, src)
# define GMTIME_R(src, dst) gmtime_s(dst, src)
#else
# define LOCALTIME_R(src, dst) localtime_r(src, dst)
# define GMTIME_R(src, dst) gmtime_r(src, dst)
#endif

static int DiffBetweenUTCAndLocalTime(const time_t * when)
{
  time_t tloc;
  if (0 == when)
    time(&tloc);
  else
    tloc = *when;

  struct tm tm1;
  LOCALTIME_R(&tloc, &tm1);
  int isdst = tm1.tm_isdst;
  GMTIME_R(&tloc, &tm1);
  tm1.tm_isdst = isdst;
  time_t t2 = mktime(&tm1);
  return tloc - t2;
}

int ParseDateTime(const char *strDate)
{
  char sign = '+';
  int hours = 0;
  int minutes = 0;
  struct tm timeinfo;
  memset(&timeinfo, 0, sizeof(tm));

  timeinfo.tm_isdst = -1; // reset the DST, as it should be not considered in this timestamp format

  sscanf(strDate, "%04d%02d%02d%02d%02d%02d %c%02d%02d",
    &timeinfo.tm_year, &timeinfo.tm_mon, &timeinfo.tm_mday, &timeinfo.tm_hour, &timeinfo.tm_min, &timeinfo.tm_sec,
    &sign, &hours, &minutes);
  timeinfo.tm_mon -= 1;
  timeinfo.tm_year -= 1900;
  timeinfo.tm_isdst = -1;

  long offset_of_date = (hours * 60 * 60) + (minutes * 60);
  if (sign == '-')
    offset_of_date = -offset_of_date;

  time_t t = mktime(&timeinfo) - offset_of_date;
  // Please note, this was "-" instead of "+" in PR #190
  return t + DiffBetweenUTCAndLocalTime(&t);
}

time_t ParseDateTime_buers(const char *strDate)
{
  struct tm timeinfo;
  char sign = '+';
  int hours = 0;
  int minutes = 0;
  time_t retgm;

  memset(&timeinfo, 0, sizeof(struct tm));
  sscanf(strDate, "%04d%02d%02d%02d%02d%02d %c%02d%02d",
    &timeinfo.tm_year, &timeinfo.tm_mon, &timeinfo.tm_mday, &timeinfo.tm_hour, &timeinfo.tm_min, &timeinfo.tm_sec,
    &sign, &hours, &minutes);
  timeinfo.tm_mon -= 1;
  timeinfo.tm_year -= 1900;
  timeinfo.tm_isdst = -1;

  long offset_of_date = (hours * 60 * 60) + (minutes * 60);
  if (sign == '-')
    offset_of_date = -offset_of_date;
#ifdef _WIN32
  retgm = _mkgmtime(&timeinfo);
#else
  retgm = timegm(&timeinfo);
#endif
  return retgm - offset_of_date;
}

// days in each month, Jan=0
// ignore leap years, no relevance for this test
static const int days[12] = { 31,28,31,30,31,30,31,31,30,31,30,31 }; 

int main(void)
{
  int year, mon, day, hour, min;
  char str[64];
  char tstr[64];
  long all = 0, same = 0, different = 0, buersfailures = 0;
  time_t t1, t2;
  struct tm *t;

  // It will become interesting with 2034 ... 
  for (year = 2019; year <= 2033; year++)
  {
    for (mon = 1; mon <= 12; mon++)
    {
      for (day = 1; day <= days[mon - 1]; day++)
      {
        for (hour = 0; hour <= 23; hour++)
        {
          for (min = 0; min < 60; min += 15)
          {
            sprintf(str, "%04d%02d%02d%02d%02d00 +0000", year, mon, day, hour, min);
            t1 = ParseDateTime_buers(str);
            t2 = ParseDateTime(str);
            if (t1 != t2)
            {
              fprintf(stderr, "error:             UTC timestamp=%s: t1 =%.2f, t2=%.2f, diff=%.2f\n", 
                str, (double)t1, (double)t2, (double)difftime(t2, t1));
              t = localtime(&t1);
              if (t)
                fprintf(stderr, "t1 translates to local timestamp %04d%02d%02d%02d%02d%02d isdst=%d\n",
                  t->tm_year + 1900, t->tm_mon + 1, t->tm_mday, t->tm_hour, t->tm_min, t->tm_sec, t->tm_isdst);
              t = gmtime(&t1);
              if (t)
                fprintf(stderr, "t1 translates to gmt   timestamp %04d%02d%02d%02d%02d%02d isdst=%d\n",
                  t->tm_year + 1900, t->tm_mon + 1, t->tm_mday, t->tm_hour, t->tm_min, t->tm_sec, t->tm_isdst);
              t = localtime(&t2);
              if (t)
                fprintf(stderr, "t2 translates to local timestamp %04d%02d%02d%02d%02d%02d isdst=%d\n",
                  t->tm_year + 1900, t->tm_mon + 1, t->tm_mday, t->tm_hour, t->tm_min, t->tm_sec, t->tm_isdst);
              t = gmtime(&t2);
              if (t)
                fprintf(stderr, "t2 translates to gmt   timestamp %04d%02d%02d%02d%02d%02d isdst=%d\n",
                  t->tm_year + 1900, t->tm_mon + 1, t->tm_mday, t->tm_hour, t->tm_min, t->tm_sec, t->tm_isdst);
              ++different;
            }
            else
              ++same;
            t = gmtime(&t1);
            if (t)
            {
              sprintf(tstr, "%04d%02d%02d%02d%02d%02d +0000", 
                t->tm_year + 1900, t->tm_mon + 1, t->tm_mday, t->tm_hour, t->tm_min, t->tm_sec);
              if (strcmp(tstr, str) != 0)
              {
                fprintf(stderr, "OOPS, original UTC timestamp and converted to time_t and converted back timestamp differ\n");
                fprintf(stderr, "original:    %s\n", str);
                fprintf(stderr, "reconverted: %s\n", tstr);
                ++buersfailures;
              }
            }
            ++all;
          }
        }
      }
    }
  }
  fprintf(stdout, "Check %ld conversions, %ld agree, %ld disagree, %ld buersfailures\n", all, same, different, buersfailures);
  return 0;
}

`

**Comment by matthuisman** [comment]
@buers
What branch of this repo you basing that on?
Leia? Or Matrix?

Can you use something like:
https://pastebin.com/

for pasting code.
If you paste your full PVRIptvData.cpp, I'll try make a pull request for it

**Comment by buers** [comment]
@matthuisman 
You mean like this?
https://pastebin.com/TfqFBaGn
This is the modified file PVRIptvData.cpp. Original I took by clicking the link in your message at the top, where you have correctly identified the problem (https://github.com/kodi-pvr/pvr.iptvsimple/blob/6e44490841e31e149b1d71348fc29df4a04f89d9/src/PVRIptvData.cpp#L831).

The Patch will solve the reported problem (EPG times one hour off for Windows-Targets during DST). It will avoid the (less severe) problem of non-Windows targets *), that will typically show one hour off close to DST-state-change. (Or more precisely, when the DST-state of the time *processing* the EPG data and the DST-state of the actual EPG-time-stamp differ).

The patch will not solve the problem, that the code uses int instead of time_t. (So the whole code will fail year 2034 - quite some time in the future. Looks ugly to me anyway …) Anybody, that knows the whole code base better, should be able to easily judge, if ParseDateTime() function can return time_t instead of int, without any negative side effects.

A testdriver is here, just compile, i.e. gcc -Wall -O2 timetest.cpp -o timetest
https://pastebin.com/2WgTjyg4

Does anybody know, if the function timegm() is available on all pvr.iptvsimple non-window platforms? If yes, I can easily provide a similar patch, that solves the mentioned problem there *). If not, one should use @palinek's patch (after carefully checking its correctness - to me, the time corrections looks, as if it is applied with wrong sign in that patch. Maybe palinek can comment).

**Comment by matthuisman** [comment]
@buers 
The file I linked too is quite an old version now.

Could you make your changes to the below (latest version):
https://github.com/kodi-pvr/pvr.iptvsimple/blob/Matrix/src/PVRIptvData.cpp

and then upload to pastebin

**Comment by palinek** [comment]
> @palinek; have you checked your patch? To me it looks, like it uses the `DiffBetweenUTCAndLocalTime` correction with the wrong sign.

Yes, I did test it. Did you?

**Comment by buers** [comment]
@palinek, yes, I tried to test your code (with a small test driver, not within Kodi). For me, it returns wrong values. I.E. for the string "19700101100000 +0000" - this is 1st of January 1970 10:00 UTC, 10 hours = 36000 seconds after the start of the Posix epoch. So clearly, the Posix timestamp for this has to be 36000. Here your function returns 28800. At that time, at my location we were one hour in front of GMT. Your DiffBetweenUTCAndLocalTime() returns 3600. But it is subtracted from the conversion of mktime (which is assuming local timestamps, not GMT timestamps). So it is two hours off. 

A small testdriver is here: https://pastebin.com/qqqX2j53
I just deleted everything not needed. Base was your modified file: https://raw.githubusercontent.com/kodi-pvr/pvr.iptvsimple/b484d60dc4930836828a59589d3693863e5412fe/src/PVRIptvData.cpp

If I am wrong, I am happy to get corrected. BTW. the original ParseDateTime() function has not a single comment (in the original code) - so I could have misinterpreted its purpose …

**Comment by buers** [comment]
@matthuisman, 
Well, I decided to change my patch, so that it really should work on all Kodi-Platforms and at any time. My first patch did only fix the problems for Windows (which was convenient and easy, because Windows has the _mkgmtime() function). I added a portable private version of this (adapted from original Public Domain code by François Grieu). It assumes, that time_t is seconds (not guaranteed in Standard C++, but in Posix) and that the epoch starts 1970-01-01 00:00:00 UTC (dito)

https://pastebin.com/GAiH5P4E

I hope, adding this adapted Public Domain code is ok. If not, here is the fix for Windows only, which really is rather trivial:
https://pastebin.com/qXfpe2fP

**Comment by matthuisman** [comment]
@buers

I tried to make a pull request but there are a lot of changes to the file.
Mostly due to different spacing.

Here's a quick how-to make a pull request

1) Click the "fork" button in this repo

2) git clone https://github.com/buers/pvr.iptvsimple
3) git checkout -b dst-fix
3) Make your modifications to the files
4) git add .
5) git commit -m "My commit message"
6) git push

7) Create a pull request from your dst-fix branch to this matrix branch

**Comment by buers** [comment]
I don't understand, why there are a lot of changes. My diff -u2 affects less than 20 lines of the original code. https://pastebin.com/jrTd5cvP

Thanks @matthuisman. I'll resign here. Somebody from the maintainer crew should jump in. The code is clearly wrong, all Windows users affected (during DST), all users affected typically a couple of days before DST changes. You opened an issue and even pinpointed the problem over 1.5 years ago. @palinek created a patch (be it totally correct or not - it would be very easy to fix, and would solve the issue a well besides a very small window each year.) It is not difficult to understand. Sadly, it looks to me, as if there was no interest from some "maintainer crew" to fix this. Or if there really is nobody, who is actively maintaining this. Even when a patch is not perfect, it should be much easier to fix a problem with it, than it is with only an end user bug report.

I just see: I should have input "/raw" in my pastebin links (never had used pastebin before). Or you have to click raw in the browser. Maybe this is the reason you got the space changes?

Proposed fix for all platforms:
https://pastebin.com/raw/GAiH5P4E

If the public domain code is not acceptable for some reason, Windows only fix (which still fits exatly this issue #158)

https://pastebin.com/raw/qXfpe2fP

**Comment by ksooo** [comment]
There is no "maintainer crew" or even an active single maintainer . That's the problem. As we are open source, volunteers to fill this vacancy are always welcome.

**Comment by matthuisman** [comment]
@buers 
You can see what I mean by spacing changes here:
![image](https://user-images.githubusercontent.com/6225961/57657179-a3c9df00-762e-11e9-899d-22d7a2fdfe92.png)

Makes it hard to see the actual changes amongst all the spacing changes.

I'm going through now and reverting the spacing changes and trying to clean it up a bit

**Comment by matthuisman** [comment]
@buers 

I have just made the pull request here:
https://github.com/kodi-pvr/pvr.iptvsimple/pull/248/files

Does that look like all your changes are correct?

**Comment by buers** [comment]
Thanks very much @matthuisman. Can't you just apply the diff in https://pastebin.com/raw/jrTd5cvP with patch or even manually? That patch touches only one region of the code. 

Is the red page my code or the green page? Seems my editor pastes tabs as blanks or vice versa. (I tried to set it up, like I had read on a coding style page for Kodi). Maybe it works from here (just learned, that I can upload zip).

[PVRIptvData.zip](https://github.com/kodi-pvr/pvr.iptvsimple/files/3175010/PVRIptvData.zip)

**Comment by matthuisman** [comment]
Yes, but originally I think your patch was based on an old commit - not the latest Matrix branch of code.

Please check: https://github.com/kodi-pvr/pvr.iptvsimple/pull/248/files looks correct.

Travis is currently building the add-on with the changes so will be able to test on multiple platforms

UPDATE:
Travis build OK.

Can download for various platforms here:
https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-248/1/artifacts
(Will only run in Kodi Matrix - maybe we can backport to Kodi Leia?)

UPDATE 2:
Also did a pull-request with the changes against the Leia branch:
https://github.com/kodi-pvr/pvr.iptvsimple/pull/249

**Comment by buers** [comment]
Thanks, matthuisman, your patch looks correct. (I used diff to compare with the local copy I had modified, and it only shows, that you have idented the comments differently, and maybe more nicely :)

Was your initial link to Leia code? Then, Backport to Leia should be trival (if only the time code we are discussing is relevant). There was no change in the relevant function.

**Comment by palinek** [comment]
> I tried to test your code (with a small test driver, not within Kodi)...But it is subtracted from the conversion of mktime (which is assuming local timestamps, not GMT timestamps). So it is two hours off.

You're right. I must have made a mistake during my previous testing. Will correct my PR.

**Comment by palinek** [comment]
OK. Now we have 2 possible implementations... let's see if any of them will be merged :)

buers -> #249 (leia) #248 (matrix)
palinek -> #190 (leia) #251 (matrix)

**Comment by phunkyfish** [comment]
@palinek @matthuisman @buers instead of having two conflicting PRs can you decide which one makes the most sense to progress?

**Comment by matthuisman** [comment]
I personally like buers as it is less code and doesn't have a specific target for windows (less likely to break if windows api changes?)

@palinek 
Can you see anything wrong with the buers patch?

**Comment by buers** [comment]
Both patches are a big improvement to the original code.
Well, I think it won't be a surprise, that I feel that my patch (submitted by @matthuisman) has some Advantages. I first also wanted to use the idea in Palinek's patch (without knowing his patch at that time), but decided against it. From my code point of view:
+ Easier to understand, some comments inside (Proof, that @palineks patch was not  so easy to understand is, that it first had done the correction the wrong way around, and it was not straightforward - took three attempts - to convince him of that fact). 
+ Test driver (not submitted, but shown here in pastebin.com links) tested *many* different situations.
+ Correct all the time (palineks Code has a small window around DST Change, where it can be wrong by one hour - although I think, this is not a big issue, but not easy to fix at all).
+ Very fast. (Palineks method needs a couple of library calls, that all have to juggle with TZ-Settings and DST,  to be able, to correct back all that TZ correction. Reason is, that there is no Standard C or C++ function to convert UTC time-stamps to time_t. I think the speed difference - while huge for the patched function - is no practical issue)
- Depends on the fact, that the time_t epoch starts at 1970-01-01 00:00:00. This is not guaranteed by Standard C/C++ (I am not aware of any implementation, where it is not the cas) . Epoch start can only be changed by small Code Change and recompilation. (Both Patches depend on Non-Standard guaranteed assumption, that time_t is based on seconds. Unpatched broken code was also dependent on this, and I guess much more of Kodi).
+ cleaner usage of types and signedness. (And when I am more experienced with Kodi patching procedutes, a one word change will make it avoid https://en.wikipedia.org/wiki/Year_2038_problem. Some of the sorrounding code has to be patched for this as well in more ore less trivial manner)

All that said - if I had known of palinek's patch before i coded mine, I wouldn't have coded mine.

@palinek - IIRC you also had a small change to the parsing/scanning logic (which I forgot or didn't understand). To me, the original looks correct (besides missing error detection). Or did I miss anything there?

**Comment by phunkyfish** [comment]
Your pastebin links to the test driver output don’t appear to be working.

**Comment by matthuisman** [comment]
@phunkyfish 
https://pastebin.com/2WgTjyg4

**Comment by phunkyfish** [comment]
Thanks 😉

**Comment by matthuisman** [comment]
@phunkyfish

No worries.
Do you have the "power" to merge the pull request if looks OK?

I'd love to close my issue finally 👍

**Comment by phunkyfish** [comment]
I don’t have the power to merge on this repo but I can test and review the code. 

@ksooo, @afedchin can I help more with these fix issues?

**Comment by phunkyfish** [comment]
@matthuisman @buers @palinek the solution may be much cleaner if std::chrono is used.

That library is cross platform and supported in c++11.

**Comment by ksooo** [comment]
@phunkyfish I don't feel responsible for pvr.iptvsimple - all I do for this addon is to keep it buildable on API changes, if possible. It's a pity that nobody else seems to take care but please understand that my time for Kodi is limited. Like for everyone (?) else, Kodi is only a hobby for me.

Maybe @afedchin is in the mood to step up?

**Comment by phunkyfish** [comment]
Understood, I’m offering to help with it though. At least for bug fixes, reviews and minor improvements.

If that’s ok with you and @afedchin?
