### ISSUE TITLE
Support for channel numbers with decimal point

### ISSUE THREAD

**Issue by puenktchen** [kodi-pvr/pvr.iptvsimple#467]
I think the title says it all. Please add support for channel numbers like 5.1, 5.2 and so on.
Currently your addon just uses the integer part of the channel number, while Kodi will also accept the decimal part.
I've checked that against the NextPVR addon, which supports this.

**Comment by phunkyfish** [comment]
Why?

With nextpvr it is because there is the concept of sub channels with US providers and the backend also supports it.

But there is no concept of that in M3U.

**Comment by puenktchen** [comment]
In my case to interleave the iptv channels with channels from another pvr addon (sort channels by their backend number).

Anyway, why should the US iptv users do not get the numbers they are used to?

**Comment by phunkyfish** [comment]
Do you have example M3Us from providers using sub channels? Are there other players that also support it via an M3U file.

I have seen examples of neither. If it’s a de facto standard then fine. Otherwise I would rather not define a standard.

In the US it is only for ATSC broadcasts. These are not used for IPTV. Only on signals captured via a set top box as far as I’m aware.

@emveepee, what’s your experience?

**Comment by emveepee** [comment]
@phunkyfish  m3u is so non-standard it is hard question.  However I quickly checked github and this gist script would create an m3u from an ATSC HDHR tuner with major.minor  https://gist.github.com/aaearon/3e1d4958cf726066c8f55d15da7d86b4

Personally I use major minor a lot not just for ATSC.  It is useful for FM I have local internet radio I put in as 87.9-107.1 radio channels.  I also use them when I have duplicates channel number when I don't want to merge the master channels together.

**Comment by kyl416** [comment]
Subchannel numbering is not just used for ATSC, it's also used for Clear QAM digital cable and even satellite in the USA with both Dish and DirecTV. Most college campuses also use ClearQAM subchannel numbering for their internal dorm room cable system.

With the HDHomerun, you can integrate those ATSC and QAM channels into your m3u playlist, which is good if you want to supply your own guide data via xmltv instead of the limited several hours of guide data you get if you don't subscribe to their DVR service. Plus if you're using ClearQAM the HDHomeRun doesn't supply guide data unless you're lucky enough to have a cable provider who provides a virtual channel mapping fo clearQAM tuners, so the only way to get guide data is to add it yourself with xmltv.

**Comment by phunkyfish** [comment]
See: https://github.com/kodi-pvr/pvr.iptvsimple/pull/489
Testbuilds: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-489/1/artifacts

**Comment by puenktchen** [comment]
Working great! Thank you.
