### ISSUE TITLE
Problems with EPG

### ISSUE THREAD

**Issue by ghost** [kodi-pvr/pvr.iptvsimple#475]
I would like to use the EPG from my SAT>IP server using EIT data. This data is on PID 18.
Can you add please support for EIT EPG? Then I don't have to use the XMLTV EPG anymore.
For example, I use this URL in PVR IPTV Simple Plugin:

#EXTINF:-1,Discovery
#EXTVLCOPT:program=19122
rtsp://xxx.xxx.x.x:554?freq=330&msys=dvbc&sr=6900&mtype=256qam&pids=0,16,17,18,20,2300,2301,2401,2311

Where PID 18 contains the EIT for EPG.

Thank you!

**Comment by phunkyfish** [comment]
Unfortunately this is not easy to do at all.

The reason is that kodi separates the video data from the EPG data used in kodi PVR. There is simply no mechanism currently to retrieve this data from the stream and treat it as EPG data. For all other PVR add-ons this is performed by the PVR backend and the video and EPG data is retrieved separately.

**Comment by phunkyfish** [comment]
My recommendation would be to use a backend such as TV Headend to decode the EPG from the stream which you could then load as XMLTV.

**Comment by ghost** [comment]
Okay, too bad, but thanks for your recommendation.
