### ISSUE TITLE
How to play php urls that redirect to m3u8 urls?

### ISSUE THREAD

**Issue by ehaab** [kodi-pvr/pvr.iptvsimple#49]
Colud you tell me how to allow playing php redirected m3u8 urls for example:http://www.somewebsite.com/play.php?id=1234 that will redirect to real m3u8 such as http://www.externalwebsite.com/hls/video1234.m3u8?token=356888sfhjhdfuu ?currenyly your addon fails to play php urls that redirect to actual m3u8!

**Comment by Jalle19** [comment]
That's a Kodi issue, not an addon issue. Please check trac.kodi.tv if there is a ticket for this already, otherwise feel free to open one.

**Comment by SteveJobzniak** [comment]
To be exact, this problem is controlled by the "stream" input code in Kodi.

It was fixed on August 27th, 2016:

https://github.com/xbmc/xbmc/pull/10236/files

This change makes Kodi follow the redirect, get the target URL, and then use that as the base-URL for all further (relative) URL requests.

Note that the MrMC fork of Kodi does NOT have the above fix (yet)...
