### ISSUE TITLE
This is unstable software!

### ISSUE THREAD

**Issue by oomek** [kodi-pvr/pvr.iptvsimple#93]
"This is unstable software! The authors are in no way reponsible for failed playings, incorrect EPG times, wasted hours, or any other undesired effects"

This is the message displayed in Kodi when I open the Simple IPTV through the addons list.
And that's true. Since a couple of days the addon started to play up. The list of channels is failing to load 1/3 times and guide is not loading for most of the time.

Has something been done to the plugin or maybe there was some changes in the Kod's addon architecture making the Simple IPTV unreliable?

Anyone knows what is going on?

**Comment by hudokkow** [comment]
My common sense tells me not to ask but debug log, please?

**Comment by oomek** [comment]
Will you accept the log from the iptvlive.org m3u/epg or the thread will be closed as they usualy do on Kodi forum when they have concerns about the legality of streams?

**Comment by oomek** [comment]
![image](https://cloud.githubusercontent.com/assets/2974860/20811887/6b53c7e0-b807-11e6-9f37-c5578d52149c.jpg)

On the Kodi forum they say that this message was put by the addon developer, is it true?

**Comment by hudokkow** [comment]
I should know better...

**Comment by oomek** [comment]
You did not answer the question about that screenshot.
Btw, the hypocricy of the Kodi devs do not cease to amaze me. They react with a violent allergy reaction to stating the obvious. Yes 99% of Kodi users are using it to watch copyrighted content. Deal with it and stop acting like a spoiled child.

**Comment by hudokkow** [comment]
I'm sorry. Where are my manners?

Me - How can I help you, a kind, polite, valuable user?
You - My (insert random crappy stream service here) doesn't work.
Me - You need help because you can't watch content without paying (to the legit owners), using some crappy provider streaming service?
You - Yes! Now make it work.
Me - I'm very sorry for your troubles, sir. We have nothing better to do with our time and dealing with your illegal/shitty stream problems is our top priority.

Dude... GET LOST!
